version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo 'export PATH="$HOME/.local/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            make build
      - run:
          name: Run Tests
          command: |
            make test
      - run:
          name: Upload to PyPi
          command: |
            ./circle-build-package
